#!/bin/sh
if [ "$SIP2FOX_HOME" = "" ]; then
  SIP2FOX_HOME=.
fi
if [ ! -f "$SIP2FOX_HOME/lib/sip2fox.jar" ]; then
  echo "ERROR: When running sip2fox from a directory other than where it was"
  echo "       installed, you must define the SIP2FOX_HOME environment variable"
  echo "       to be the directory where it was installed."
  exit 1
fi
(exec java -Xms64m -Xmx96m -Djava.endorsed.dirs=$SIP2FOX_HOME/lib -jar $SIP2FOX_HOME/sip2fox.jar $1 $2 $3 $4 $5 $6 $7 $8 $9)
exit 0
